version: '3'

services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db
        env_file:
          - ./.env
        environment:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${SQL_PASS}
        ports:
          - "1433:1433"
        volumes:
          - /home/db/  
    aromashop.mvc:
        image: gbariel/aroma:latest
        container_name: aroma_app
        restart: always
        ports:
         - "5000:80"
        depends_on:
         - db
        volumes:
         - /home/app/
        environment:
           ASPNETCORE_ENVIRONMENT: Development
    sqlpad:
        image: sqlpad/sqlpad
        container_name: sqlpad
        env_file:
          - ./.env
        ports:
         - "3000:3000"
        environment:
           SQLPAD_ADMIN: ${SQLPAD_LOGIN}
           SQLPAD_ADMIN_PASSWORD: ${SQLPAD_PASS}
        volumes:
           - /home/sqlpad
